#!/bin/bash

set -e

echo -e "\nCreating installation directory\n"
cd
sudo rm -rf /tmp/installitrude/gertrude-cli/
mkdir /tmp/installitrude/gertrude-cli
cd /tmp/installitrude/gertrude-cli

# INSTALLATION OF LUAROCKS
LR=$(which luarocks)

if [ ! -f $LR ]; then
    wget https://luarocks.org/releases/luarocks-3.9.2.tar.gz
    tar zxpf luarocks-3.9.2.tar.gz
    cd luarocks-3.9.2
    ./configure && make && sudo make install
    LR=$(which luarocks)
    if [ -f $LR ]; then
        echo -e "\n\e[32mLuarocks Installed successfully\e[0m\n"
    fi
else
    echo -e "\n\e[32mLuarocks is already installed\e[0m\n"
fi

# INSTALLATION OF LUAFILESYSTEM
LR=$(luarocks list | grep "luafilesystem")
if [[ $LR = "luafilesystem" ]]; then
    echo -e "\n\e[32mLuaFileSystem already Installed\e[0m\n"
else
    sudo luarocks install luafilesystem
    echo "require \"lfs\"" | lua
    LR=$(luarocks list | grep "luafilesystem")
    if [[ $LR = "luafilesystem" ]]; then
        echo -e "\n\e[32mLuaFileSystem Installed successfully\e[0m\n"
    else
        echo -e "\n\e[31mLuaFileSystem Installation failed\e[0m\n"
    fi
fi

# REMOVING INSTALLATION DIR
echo "Removing installation directory..."
cd
sudo rm -rf /tmp/installitrude/gertrude-cli/
echo -e "\n\e[32mDependencies Installation complete!\e[0m\n"

read -N 1 -p "Press any key to continue" placeholder
